// <auto-generated />
using System;
using ApiMonetizationGateway.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMonetizationGateway.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251109200313_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMonetizationGateway.Core.Entities.ApiUsageLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LogId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("CustomerId", "Timestamp");

                    b.ToTable("ApiUsageLogs");
                });

            modelBuilder.Entity("ApiMonetizationGateway.Core.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomerId");

                    b.HasIndex("ApiKey")
                        .IsUnique();

                    b.HasIndex("TierId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            ApiKey = "asftdtyfqwy2332jb423ui4b3u2b324",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "umair@gmail.com",
                            IsActive = true,
                            Name = "Umair",
                            TierId = 1,
                            UserId = new Guid("5cd25fa8-b3b3-4926-96b3-aa111c9fee75")
                        },
                        new
                        {
                            CustomerId = 2,
                            ApiKey = "qwftwefqwy2332jb423ui4b3u2b334",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ali@gmail.com",
                            IsActive = true,
                            Name = "Ali",
                            TierId = 2,
                            UserId = new Guid("6cd23fa8-b3b3-4926-96b3-aa111c9fee55")
                        });
                });

            modelBuilder.Entity("ApiMonetizationGateway.Core.Entities.MonthlyUsageSummary", b =>
                {
                    b.Property<int>("SummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SummaryId"));

                    b.Property<decimal>("AmountBilled")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MonthYear")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("int");

                    b.HasKey("SummaryId");

                    b.HasIndex("CustomerId");

                    b.ToTable("MonthlyUsageSummary");
                });

            modelBuilder.Entity("ApiMonetizationGateway.Core.Entities.Tier", b =>
                {
                    b.Property<int>("TierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TierId"));

                    b.Property<int>("MonthlyQuota")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RateLimit")
                        .HasColumnType("int");

                    b.HasKey("TierId");

                    b.ToTable("Tiers");

                    b.HasData(
                        new
                        {
                            TierId = 1,
                            MonthlyQuota = 100,
                            Name = "Free",
                            Price = 0m,
                            RateLimit = 2
                        },
                        new
                        {
                            TierId = 2,
                            MonthlyQuota = 100000,
                            Name = "Pro",
                            Price = 50.00m,
                            RateLimit = 10
                        });
                });

            modelBuilder.Entity("ApiMonetizationGateway.Core.Entities.ApiUsageLog", b =>
                {
                    b.HasOne("ApiMonetizationGateway.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ApiMonetizationGateway.Core.Entities.Customer", b =>
                {
                    b.HasOne("ApiMonetizationGateway.Core.Entities.Tier", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("ApiMonetizationGateway.Core.Entities.MonthlyUsageSummary", b =>
                {
                    b.HasOne("ApiMonetizationGateway.Core.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
